services:
  redis:
    image: redis:7.4.1
    container_name: lb-websock-redis
    restart: always
    ports:
      - "6380:6379"
  server1:
    image: docker.io/library/websockets:0.0.3
    container_name: lb-websock-s1
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - HOST_NAME=0.0.0.0
      - REDIS_PORT=6380
      - REDIS_HOST_NAME=host.docker.internal
  server2:
    image: docker.io/library/websockets:0.0.3
    container_name: lb-websock-s2
    restart: always
    ports:
      - "3002:3000"
      - "3003:3001"
    environment:
      - HOST_NAME=0.0.0.0
      - REDIS_PORT=6380
      - REDIS_HOST_NAME=host.docker.internal