services:
  redis:
    image: redis:7.4.1
    container_name: websock-dev-redis
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    container_name: websocket-dev-postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: websocket
      POSTGRES_PASSWORD: websocket
    ports:
      - "5432:5432"